json.shop_views @shop_views
json.shop_view_ids @shop_view_ids
json.shop_product_views @shop_product_views
json.shop_product_view_ids @shop_product_view_ids
json.orders @orders
json.order_ids @order_ids
json.product_orders @product_orders
json.product_order_ids @product_order_ids
json.shop_products @shop_products
json.shop_product_ids @shop_product_ids