json.reviews @happy_reviews
json.reviewIds @review_ids
json.products @products
json.productIds @product_ids
json.users @users
json.userIds @user_ids
json.mostViewedShop @most_viewed_shop
json.mostOrderedShop @most_ordered_shop
json.mostBoughtProduct @most_bought_product